services:
  mongo:
    image: mongo:latest
    container_name: mongo-nebuloid-dev
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

volumes:
  mongo_data:
  mongo_config:

# This file is created to run a MongoDB database on your system for development.
# To run this file, first open Docker Desktop, and then run `docker-compose up -d`.
# To ensure success, be sure that port 27017 is already cleared of services before starting.
# ---
# This file was made with the help of a blogpost. Here's the article on the web:
# https://anthonysimmon.com/the-only-local-mongodb-replica-set-with-docker-compose-guide-youll-ever-need/
