type Query {
	# Courses
	course(id: ID!): Course
	indexCourses: [Course!]

	# Projects
	project(id: ID!): Project
	indexProjects: [Project!]
}

type Course @entity {
	id: ID! @id
	name: String! @column
	description: String @column
	projects: [Project!] @link
}

type Project @entity {
	id: ID! @id
	name: String! @column
	description: String @column
	courses: [Course!] @link
}
